---
- name: Set elasticsearch_major_version
  set_fact: "elasticsearch_major_version={{ elasticsearch_version.split('.')[0] }}.x"
  when: elasticsearch_major_version is undefined

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Create Configuration Directory
  file:
    path: "{{ elasticsearch_conf_dir }}"
    state: directory
    owner: root
    group: "{{ elasticsearch_group }}"
    mode: "2750"

- name: Create PID Directory
  file:
    path: "{{ elasticsearch_pid_dir }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: "0755"

- name: Create Data and logs directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: "2750"
  with_items:
    - "{{ elasticsearch_log_dir }}"
    - "{{ elasticsearch_data_dirs }}"

- name: Create snapshot directories
  file:
    path: "{{ elasticsearch_snapshot_path }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: "2750"
  when: elasticsearch_snapshot_path is defined

- name: Copy Configuration File
  template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    owner: root
    group: "{{ elasticsearch_group }}"
    mode: "0660"
    force: true
  notify: Restart elasticsearch

- name: Copy Default File
  template:
    src: elasticsearch.j2
    dest: "{{ elasticsearch_default_file }}"
    owner: root
    group: "{{ elasticsearch_group }}"
    mode: "0660"
    force: true
  notify: Restart elasticsearch

- name: Copy jvm.options File
  template:
    src: jvm.options.j2
    dest: "{{ elasticsearch_conf_dir }}/jvm.options"
    owner: root
    group: "{{ elasticsearch_group }}"
    mode: "0660"
    force: true
  notify: Restart elasticsearch

- name: Cron for Elasticsearch snapshots
  template:
    src: elasticsnap.j2
    dest: "/etc/cron.daily/elasticsnap"
    owner: root
    group: "{{ elasticsearch_group }}"
    mode: "0750"
  when: elasticsearch_snapshot_path is defined and elasticsearch_snapshot_name is defined

- name: Copy elasticsearch.service (Debian 10)
  template:
    src: elasticsearch.service.j2
    dest: "/lib/systemd/system/elasticsearch.service"
    owner: root
    group: root
    mode: "0640"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'

- name: Flush handlers
  meta: flush_handlers

- name: Make sure elasticsearch is started
  service:
    name: elasticsearch
    state: started
    enabled: true
  when: elasticsearch_start_service
  register: elasticsearch_started
  notify: Wait for elasticsearch to startup
