---

- name: Install pre-requisite (Debian)
  apt:
    name: [ca-certificates, apt-transport-https, curl]
    state: present

- name: Add Elasticsearch repository key (Debian)
  apt_key:
    url: '{{ elasticsearch_apt_key }}'
    id: '{{ elasticsearch_apt_key_id }}'
    state: present

- name: Add elasticsearch repository (Debian)
  apt_repository:
    repo: '{{ elasticsearch_apt_url }}'
    state: present

- name: Ensure elasticsearch is installed (Debian)
  apt:
    name: '{{ elasticsearch_package_name }}{% if elasticsearch_version is defined %}={{ elasticsearch_version }}{% endif %}'
    state: present
    allow_unauthenticated: "{{ 'no' if elasticsearch_apt_key else 'yes' }}"
    cache_valid_time: 86400
  register: elasticsearch_debian_install_from_repo
  notify: Restart elasticsearch
  environment:
    ES_PATH_CONF: "{{ elasticsearch_conf_dir }}"

- name: Hold elasticsearch version (Debian)
  dpkg_selections:
    name: "{{ elasticsearch_package_name }}"
    selection: "hold"
  when: elasticsearch_version_lock
