---
- name: Restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: true
  when: elasticsearch_start_service
  register: elasticsearch_restarted
  notify: Wait for elasticsearch to startup

- name: Wait for elasticsearch to startup
  wait_for:
    host: "{{ elasticsearch_api_host }}"
    port: "{{ elasticsearch_api_port }}"
    delay: 5
    connect_timeout: 1
  when: elasticsearch_start_service and elasticsearch_restarted is defined and (elasticsearch_restarted.changed or elasticsearch_started)
